version: '3'

services:
  app:
    image: test1
    container_name: test1
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env

  mongodb:
    image: mongo:4.4-bionic
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mongodata:/data/db
    ports:
      - "27018:27017"

volumes:
  mongodata: